apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: elk

data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        storage.path  /var/log/flb-storage
        storage.sync  normal
        storage.checksum off
        storage.backlog.mem_limit 50M

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            cri
        Mem_Buf_Limit     20MB
        Skip_Long_Lines   On
        Refresh_Interval  5
        Read_from_Head    True
        DB                /var/log/flb_kube.db

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off
        Kube_Tag_Prefix     kube.var.log.containers.
        Kube_URL            https://kubernetes.default.svc:443

    [OUTPUT]
        Name                es
        Match               *
        Host                elasticsearch
        Port                9200
        Index               kubernetes-logs
        Suppress_Type_Name  On
        Logstash_Format     Off
        Retry_Limit         False

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
